import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { API_HOLIDAZE_URL } from '../../utils/constans';

/**
 * API slice for managing Venue data using Redux Toolkit Query.
 *
 * This API slice provides a structured way to declare how to fetch data from the 'Holidaze' API server.
 * It sets up endpoints to fetch individual venue details and a list of venues. It uses caching tags to
 * manage invalidation and re-fetching, ensuring that the UI can react to updates in the data layer.
 *
 * Exports hooks automatically generated by RTK Query for performing the API actions in React components.
 *
 * @module apiSlice
 */

export const apiSlice = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({ baseUrl: API_HOLIDAZE_URL }),
  tagTypes: ['Venue', 'Venues'],
  endpoints: (builder) => ({
    getVenue: builder.query({
      query: (id) => `/venues/${id}`,
      providesTags: ['Venue'],
    }),
    getVenues: builder.query({
      query: () => '/venues',
      providesTags: ['Venues'],
    }),
  }),
});

export const { useGetVenueQuery, useGetVenuesQuery } = apiSlice;
